unbind C-b 
bind C-b source-file ~/.config/tmux/tmux.conf

# set-option -g prefix C-a
#bind-key C-a send-prefix

# Disable enforced 500ms delay
set-option -sg escape-time 10
# Enable copy/past to clipboard
set -g set-clipboard on


# List of plugins
set -g @plugin 'tmux-plugins/tpm'
# set -g @plugin 'tmux-plugins/tmux-sensible'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

set -g @plugin 'catppuccin/tmux#v2.1.1'
set -g @catppuccin_flavor 'macchiato' # latte, frappe, macchiato or mocha
set -g @plugin 'christoomey/vim-tmux-navigator'

# vim tmux navigator key mappings
set -g @vim_navigator_mapping_left "C-H"
set -g @vim_navigator_mapping_right "C-L"
set -g @vim_navigator_mapping_up "C-Left C-k"
set -g @vim_navigator_mapping_down "C-Left C-j"
set -g @vim_navigator_mapping_prev ""  # removes the C-\ binding

# Set new panes to open in current directory
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

