console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[upgrade]
  source = 'cdn'
  interval = '168h'
  auto = false
  notice = false

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'session'
    template = "{{ .UserName }}@{{ .HostName }}"
    style = 'powerline'
    powerline_symbol = ''
    leading_powerline_symbol = '█'
    background = 'p:blue'
    foreground = 'p:background'

  [[blocks.segments]]
    type = 'path'
    style = 'powerline'
    powerline_symbol = ''
    background = 'p:lavender'
    foreground = 'p:background'

    [blocks.segments.properties]
        style = 'full'

  [[blocks.segments]]
    type = 'text'
    style = 'powerline'
    powerline_symbol = ''
    template = '{{ if .Env.TMUX }}tmux{{ end }}'
    background = 'p:mauve'
    foreground = 'p:background'

[[blocks]]
    type = 'rprompt'
    overflow = 'hidden'

    [[blocks.segments]]
        type = 'git'
        style = 'plain'
        foreground = 'p:os'
        background = 'transparent'
        template = '{{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }}'
        
        [blocks.segments.properties]
            branch_icon = ''
            commit_icon = '@'
            fetch_status = true
    

[palette]
    os = "#ACB0BE"
    closer = "p:os"
    pink = "#F5C2E7"
    lavender = "#B4BEFE"
    blue = "#89B4FA"
    mauve = '#cba6f7'
    background = "#1e1e2e"
